name: Deploy raincloud plot

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir -p docs
          cp -r PEC2/scripts/_build/html/* docs/
